# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        nim: ["devel", "stable", "2.2.0", "2.0.0", "1.6.0", "1.4.0", "1.2.0"]

    name: Nim ${{ matrix.nim }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CHOOSENIM_CHOOSE_VERSION: ${{ matrix.nim }}
    steps:
      - run: sh curl https://nim-lang.org/choosenim/init.sh -sSf | sh
      - run: nimble buildExamples
